// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu9PS19QLsOoBx24ey6MHkHZ07r5lEbPo',
    appId: '1:287922947207:web:f6430c9c4d46a823d26422',
    messagingSenderId: '287922947207',
    projectId: 'app-ploychat',
    authDomain: 'app-ploychat.firebaseapp.com',
    storageBucket: 'app-ploychat.firebasestorage.app',
    measurementId: 'G-RKD8E81R0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI_q8oOXK4vyheCsS__4oGx3gjJVT4tHk',
    appId: '1:287922947207:android:ddee9b7220684269d26422',
    messagingSenderId: '287922947207',
    projectId: 'app-ploychat',
    storageBucket: 'app-ploychat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiI7yX1y2J0_A6eG8Y0-UKocAxaCKFzW8',
    appId: '1:287922947207:ios:b8e3a3093002dae9d26422',
    messagingSenderId: '287922947207',
    projectId: 'app-ploychat',
    storageBucket: 'app-ploychat.firebasestorage.app',
    iosBundleId: 'com.example.polychat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiI7yX1y2J0_A6eG8Y0-UKocAxaCKFzW8',
    appId: '1:287922947207:ios:b8e3a3093002dae9d26422',
    messagingSenderId: '287922947207',
    projectId: 'app-ploychat',
    storageBucket: 'app-ploychat.firebasestorage.app',
    iosBundleId: 'com.example.polychat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu9PS19QLsOoBx24ey6MHkHZ07r5lEbPo',
    appId: '1:287922947207:web:abab51c4e4b8ef9dd26422',
    messagingSenderId: '287922947207',
    projectId: 'app-ploychat',
    authDomain: 'app-ploychat.firebaseapp.com',
    storageBucket: 'app-ploychat.firebasestorage.app',
    measurementId: 'G-1RXMS47RRY',
  );
}
